---
title: Mark Engel
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    section: post
email: your-email@example.com
description: The portfolio of California-based artist Mark Engel.
baseurl: ''
url: https://mark-engel.com
permalink: "/blog/:title"
section: true
netlifycms: true
analytics: false
sass:
  style: compressed
  sass_dir: _sass
compress_html:
  clippings: all
plugins:
- jekyll-sitemap
markdown: kramdown
kramdown:
  auto_ids: false
exclude:
- README.md
- LICENSE.txt
- netlify.toml
- feed.xml
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
